### ISSUE TITLE
Create a Sharepoint adaptor to fetch files from a Sharepoint site 

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/akf#1]
## Background, context, and business value
The [Aga Khan Foundation (AKF)](https://the.akdn/en/how-we-work/our-agencies/aga-khan-foundation) has requested that OpenFn automate financial reporting from Business Central  to Salesforce in order to provide better visibility into the organization's financial operations.

The Business Central data will be exported as CSV files and posted to a Sharepoint site. **OpenFn will fetch the CSV files from the Sharepoint site, convert the data to JSON, and then transform and load the data to Salesforce.**  

## The specific request, in as few words as possible
In our API exploration, we have not been successful at fetching files from the Sharepoint site using the API. We have been able to do this via the front end using the steps below. 
1. Navigate and log in to the Sharepoint site using this LP cred: `AKF Sharepoint Site`
2. Download any of the files in the `Document` tab of the left-hand menu. Also accessible via this [link](https://akdngva.sharepoint.com/sites/AKFDataIntegrations/Shared%20Documents/Forms/AllItems.aspx). 

**First, prototype fetching files from a Sharepoint site using HTTP, then create a Sharepoint adaptor that can be used to fetch files from a Sharepoint site.** 

Note: there are two APIs that can be used to interact with Sharepoint. Please do some analysis on which is the best for our purposes. 
1. [Microsoft Graph API ](https://learn.microsoft.com/en-us/graph/api/resources/sharepoint?view=graph-rest-1.0#sharepoint-api-root-resources): from the API documents it looks like this API requires an `access_token` which can be generated directly in the [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) once the user is signed in (see image below). 
<img width="1435" alt="image" src="https://github.com/OpenFn/akf/assets/80456839/4fe62600-9f2e-4a7f-970a-e768fb4053ae">

2. [Sharepoint API ](https://learn.microsoft.com/en-us/sharepoint/dev/sp-add-ins/get-to-know-the-sharepoint-rest-service?tabs=csom): from the API documents, it looks like the Sharepoint API requires a `clientID` and `clientSecret` (please validate if this is true and something that we need to request from the client. )

## state.json

```json
{
  "configuration": { "See LP: AKF Sharepoint Site" },
  "data": { "NA"},
}
```

## adaptor
Prototype using the `HTTP` adaptor, then create a `SharePoint` adaptor

## Toggl 
`AKF BC M3 - Integration Setup`

**Comment by daissatou2** [comment]
@mtuchi please sync with Taylor for this issue to discuss an approach since it looks like there are 2 APIs we might connect with (Sharepoint OR Graph). You can also take a look at this past Sharepoint demo Taylor worked on
https://github.com/OpenFn/amp-demo/blob/master/jobs/01-amp-to-sharepoint.js

**Comment by mtuchi** [comment]
@aleksa-krolls i am still stuck on getting the access token, this is the error that i facing 
```
{"error_description":"Exception of type 'Microsoft.IdentityModel.Tokens.AudienceUriValidationFailedException' was thrown."}
```

My last research landed me to this answer https://learn.microsoft.com/en-us/answers/questions/764631/getting-exception-of-type-microsoft-identitymodel

i think i need to pair with @taylordowns2000 to unblock me on this. I will snyc with Taylor in the AM tomorrow

**Comment by aleksa-krolls** [comment]
hey @mtuchi is this adaptor now live and ready to use? 
(Sorry if I missed any updates when I was out on Friday. thanks!)

**Comment by mtuchi** [comment]
> hey @mtuchi is this adaptor now live and ready to use? (Sorry if I missed any updates when I was out on Friday. thanks!)

@aleksa-krolls the adaptor is ready, but it doesn't have sharepoint functions. Currently it has two generic function `get()` and `create()` which is enough for us to start. There is already an issue for adding sharepoint function to the adaptor https://github.com/OpenFn/adaptors/issues/284 which is next in my backlog
