### ISSUE TITLE
New job to "clear actuals" when not updated in the sync

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/akf#18]
## Background, context, and business value
Sometimes accounting people might update BC data to delete rows, or change values (e.g., from `blank` to `ProjectCode2`... or from `ProjectCode1` to `ProjectCode22`). 

In such scenarios, we will need to overwrite previously synced actuals in AIMS to reflect what data is _currently_ in Business Central. 

For this workflow, we assume that (1) BC data is _always_ the source of truth, and (2) actuals data will _never_ get entered in AIMS (AIMS should always match BC exactly).  

## The specific request, in as few words as possible
To achieve this, after we run the current workflow (jobs 1-5), we want to add a step to `loadFinancialstoSf.js` that will: 

1. Check Salesforce for `Financials` not modified by the bulk upsert operation (currently in that job). 
2. If there are `Financials` _not_ updated since that upsert operation started, then we assume that these Financial records have been corrected since the last sync. Therefore, we want to...
3. Upsert these `"financialsToCorrect"` to set `Amount_Actual__c === 0` to "clear" out the value that was entered in the last sync. (This will help to overwrite bad data that has since been updated in Business Central.)

### To achieve this functionality, we propose: 

**(1) Editing the job 4 `loadFinancialstoSf.js`** 
Please log the `runStartTime` and then send a notification when that job run finishes. 

Job operations will look something like...
```
console.log(runStartTime); 
bulkUpsert(AllCleanedFinancials); 
post(messageToInbox); 
```
*Note that the new `post()` operation should run always _after_ the Salesforce `upsert()`. And it should run even if Salesforce returns a failure response (`400` or `500` exit code). Therefore...
If the Salesforce `upsert()` fails, we should still (i) `post(message)`... and then (ii) log errors from the failed upsert. 

This notification message should looks something like this (if possible): 
```
{"notification_type": "workflow-completed", 
"workflowStartTime": "{runStartTimeFromJob4}", 
"triggerDateTime": "{nowDateTime}", 
"bcUpload": "{fileNameFromJob1}"
}
```

**(2) Create a new message filter 6th job called `clearCorrectedFinancials.js`.** 
This job will be triggered by the notification message sent in the step prior. This job will include two steps: 
1. Query Salesforce to get `financialsToCorrect`: 
```
SELECT Id, LastModifiedDate, Amount_Actual__c, External_Id__c from ampi__Financial__c WHERE Amount_Actual__c!=0 AND LastModifiedDate < {runStartTimeFromJob4}
```
2. Upsert these `financialsToCorrect` (object name `ampi__Financial__c`) with the following mappings: 
```
{Id: queryResponse.Id, 
Amount_Actual__c: 0 }
```
Please [see this spreadsheet](https://docs.google.com/spreadsheets/d/1IlerWIAA1BUO3upQ5TLSMR6wTsWHCVbvchUg5LsFv44/edit#gid=817112558) for our design thinking scratch pad. 

### Expected data volumes
We expect this Salesforce query that returns `financialsToCorrect` to not return more than a couple thousand records. 

## state.json
Please work on a new branch that we can later merge to `staging` for testing. 

Job 4 `loadFinancialstoSf.js`: 
```
{
  "configuration": { "See LP: AKF Salesforce Sandbox - Partial 2023" },
  "data": { "generated by job 3"},
  "inboxURL": {see openfnorg project}
```

Job 6 `clearCorrectedFinancials.js`: 
```
{
  "configuration": { "See LP: AKF Salesforce Sandbox - Partial 2023" },
  "data": { "generated by job 4"},
  "runStartTime": { "generated in job 4"},
}
```

## expression.js
Existing job 4: `loadFinancialstoSf.js`

New job 6: `clearCorrectedFinancials.js`

### adaptor
`salesforce` for both

### trigger
New job 6 will be based on `message filter` trigger type 

### output
New job should log EVERYTHING, including the runDateTime, the query sent to Salesforce, and the data returned. 

## Toggl 

`AKF BC M8 - Exception Reporting`

**Comment by mtuchi** [comment]
@aleksa-krolls why this job needs have a message trigger ?, why flow trigger when `loadToSf` job succeed ?

**Comment by mtuchi** [comment]
The query in this issue is not correct, here is the updated query 
```
SELECT Id, LastModifiedDate, Amount_Actual_Local_Currency__c, ExternalId__c from ampi__Financial__c WHERE Amount_Actual_Local_Currency__c != 0 AND Amount_Actual_Local_Currency__c != NULL AND LastModifiedDate < ${state.data.runStartTime}
```

**Comment by mtuchi** [comment]
@daissatou2 here you go #22 ,
I have tested with `09_14` file and the `openfnInboxUrl` from `AKF BC - AIMS Integration`
Please setup the job on platform app and don't for get to add 
`openfnInboxUrl: AKF BC - AIMS [Staging]` and `apiVersion: 59` in your salesforce credentials 

cc @aleksa-krolls

**Comment by daissatou2** [comment]
@aleksa-krolls FYI we updated the query after Mtuchi noticed some records where `Amount_Actual_Local_Currency__c` == null.

But I think we need to update it further so we do not clear actuals from previous years. The query below is working in the developer console. Thoughts? 
`SELECT Id, LastModifiedDate, Amount_Actual_Local_Currency__c, ExternalId__c from ampi__Financial__c WHERE Amount_Actual_Local_Currency__c != 0 AND Amount_Actual_Local_Currency__c != NULL AND LastModifiedDate < ${state.data.runStartTime} AND ampi__Budget__r.ampi__End_Date__c = ${lastDayOfYear}`

**Comment by daissatou2** [comment]
@mtuchi I am getting this [error](https://openfn.org/projects/akf-bc-aims-staging/runs/06514cb0-6f34-71df-8dde-30acb7c9600c) on platform. I tested with both the v4.2.1 of the SF adaptor (which is what we've been using so far) and with the @latest version. I have dm'd you the cred I am using.

**Comment by mtuchi** [comment]
@daissatou2 i have fixed it here [84ffc60](https://github.com/OpenFn/akf/commit/84ffc60347fdcd9abda9f2edb1bc4e9521aed565)
And you need to update credentials to use `AKF Salesforce Sandbox + apiVersion - Partial 2023` for all salesforce jobs. I have already added the credential to `AKF BC -> AIMS [STAGING]`

**Comment by aleksa-krolls** [comment]
@daissatou2 @mtuchi I think we need update the query slightly. For the last criteria...

Instead of `AND ampi__Budget__r.ampi__End_Date__c = ${lastDayOfYear}`

Let's use `AND Reporting_Period_Start_Date__c >= {CurrentYear}-01-01` (because I worry users might end up creating budgets that span multiple years; reporting period is a more reliable filter)

Full query: 
```SELECT Id, LastModifiedDate, Amount_Actual_Local_Currency__c, ExternalId__c from ampi__Financial__c WHERE Amount_Actual_Local_Currency__c != 0 AND Amount_Actual_Local_Currency__c != NULL AND LastModifiedDate < ${state.data.runStartTime} AND Reporting_Period_Start_Date__c > {CurrentYear}-01-01
```

**Comment by mtuchi** [comment]
@aleksa-krolls this query 👇🏽  returns `0` results 
```
SELECT Id, LastModifiedDate, Amount_Actual_Local_Currency__c, ExternalId__c from ampi__Financial__c WHERE Amount_Actual_Local_Currency__c != 0 AND Amount_Actual_Local_Currency__c != NULL AND LastModifiedDate < 2023-09-28T10:54:52.658Z AND Reporting_Period_Start_Date__c >= 2023-01-01
```
cc @daissatou2

**Comment by daissatou2** [comment]
looks great! @mtuchi
