### ISSUE TITLE
Create 2 new jobs to fetch a CSV from Sharepoint, convert to JSON, then transform, map and upsert `Financial__c` records in SF

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/akf#2]
## Background, context, and business value

The [Aga Khan Foundation (AKF)](https://the.akdn/en/how-we-work/our-agencies/aga-khan-foundation) has requested that OpenFn automate financial reporting from Business Central to Salesforce in order to provide better visibility into the organization's financial operations.

The Business Central data will be exported as CSV files and posted to a Sharepoint site. **OpenFn will fetch the CSV files from the Sharepoint site, convert the data to JSON, *aggregate*, and then transform and load the data to Salesforce.**

**Read through [these slides](https://docs.google.com/presentation/d/1SEccepF2Cjo_53H_B6c0xSYHf8J96fndzv4r5poJafM/edit#slide=id.g257002e657f_0_12) for an overview of how the budgeting process might work.** 

## The specific request, in as few words as possible

Create two jobs to get and load data.

**Job 1: getActuals.js** 
1. Fetch a CSV file named `bc_actuals_export_10072023.csv` from the AKF SharePoint site at this [link](https://akdngva.sharepoint.com/sites/AKFDataIntegrations/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FAKFDataIntegrations%2FShared%20Documents%2FBC%20Actuals%20Exports&viewid=5c371667%2D066c%2D4ad8%2D8e1a%2Da05448979955). 
2. Convert this file from CSV to JSON format 

**Job 2: aggregateFinancials.js** 
1. Aggregate, transform, map and load the data to Salesforce by upserting `Financial__c` records. 
- To aggregate, group CSV rows by `GrantCode`, `CostCenter`, and `ProjectCode`, and then SUM the `Sum of Actual` field.  
- Map the aggregate data to Salesforce `ampi__Financial__c` records using this *[mapping specification document](https://docs.google.com/spreadsheets/d/1h6Vnx7jR_PHbSiv1H33O51580lLMEPAvodPqJqbD9MA/edit#gid=1275153608)*. 
3. The unique id for upsert is `ExternalId__c` which will be a combination of `GrantCode`, `Posting Month`, `Posting Year`, `Project Code`, `Cost Center` and `Unit` from the source data. 

[**See workflow diagram**](https://lucid.app/lucidchart/ce62ffb2-1e89-4b09-8e7c-ab6b6d9453b6/edit?invitationId=inv_c3d849fb-a2f2-4b5a-8038-219e2afca71f&page=Ky6aWu9PHhAa#)
<img width="1085" alt="image" src="TOREPLACE">

### Expected data volumes
TBD - but we expect CSVs to have sometimes 20k-100k rows

## state.json

**Job 1**
```json
{
  "configuration": { "See LP: AKF Sharepoint Site" },
  "data": { "NA"},
}
```

**Job 2**
```json
{
  "configuration": { "See LP: AKF Salesforce Sandbox - Partial 2023" },
  "data": { "NA"},
}
```

## expression.js
We need to build 1 workflow with 2 job steps to get and then load the data: 
**Job 1:** 
- cron trigger, new MS Graph adaptor* 
- Fetch CSV from Sharepoint and convert to JSON

*_Take a look at this previous[ GH issue](https://github.com/OpenFn/akf/issues/1) to develop the new Sharepoint/MS Graph adaptor for more details._

**Job 2:** 
- flow trigger, SF adaptor
- Aggregate, transform, map, and upsert records to SF

## output
Your input will have `511` rows of data, but your aggregated output should have `30` rows. 
- See the `bc_actuals_export_sample` tab in this [sheet](https://docs.google.com/spreadsheets/d/1k1H1sTYTk3hcX5UtD9Te6Y1bxAsZL0de/edit#gid=947827665) for an example of what this file will look like. 
- See the [aggregated output sheet](https://docs.google.com/spreadsheets/d/1k1H1sTYTk3hcX5UtD9Te6Y1bxAsZL0de/edit#gid=997706999) for how these CSV rows should be aggregated by `GrantCode`, `CostCenter`, and `ProjectCode` before they are mapped to the SF data model. 

## Toggl 
`AKF BC M3 - Integration Setup`

**Comment by aleksa-krolls** [comment]
@taylordowns2000 FYI this is the issue @mtuchi is working on where we will first use the new `msgraph` adaptor. I'm wondering if aggregation should happen in job 1 vs. job 2 to optimize for performance

**Comment by mtuchi** [comment]
@daissatou2 this is ready for review #3 , i am merging this so that you can test on platform-app, Remember to use the AKF testing project and `mtuchi-akf` credentials for `getActuals` job

1st `getActuals` | adaptor: `msgraph@v0.2.0` | credentials: `mtuchi-akf`
2nd `applyMappings` | adaptor: `common@v1.10.2` 
3rd `loadFinancialsToSf` | adaptor: `salesforce@v4.0.5` | credentials: `See LP: AKF Salesforce Sandbox - Partial 2023`
cc @aleksa-krolls
