### ISSUE TITLE
Add cursor to get actuals job

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/akf#4]
## Background, context, and business value
We have received details from the client about how to implement the cursor for job 1. 

See #2 for more background information. 

## The specific request, in as few words as possible
Update job 1 [getActuals.js](https://github.com/OpenFn/akf/blob/staging/jobs/getActuals.js) to:
1. Fetch a CSV file with the naming convention below from the AKF SharePoint site at this [link](https://openfnorg.sharepoint.com/Shared%20Documents/Forms/AllItems.aspx). (Implement this to work with the OpenFn Sharepoint site until we get API access to the AKF site).
2. You should always get the most recent file in a folder called “BC Actuals Export”. 
3. You will know which file is most recent by parsing the date from the file name.  Note: we have control over how we want the file to be named. **Please let us know which naming convention would make parsing the date the simplest, if any.** For example, should we use bc_actuals_YY_MM_DD.csv, YY_MM_DD_bc_actuals.csv, or something else? 

### Expected data volumes
TBD - but we expect CSVs to have sometimes 20k-100k rows

## state.json

```json
{
  "configuration": { "OpenFn Sharepoint Site (see comment below)" },
  "data": { "NA"},
}
```

### job name 
getActuals.js
### adaptor 
MS Graph
### trigger 
Cron
### operation 
GET
### output/testing

Please use the OpenFn Sharepoint site to test until we get access to the AKF Sharepoint site. 
With the files currently in the `bc_actuals_export` [folder](https://openfnorg.sharepoint.com/Shared%20Documents/Forms/AllItems.aspx?id=%2FShared%20Documents%2FBC%20Actuals%20Export&viewid=aaf19eb4%2D2159%2D42a1%2D81e9%2Da392b96bc5e4), your job should return the file named `bc_actuals_23_06_10.csv`

## Toggl 
AKF BC M3 - Integration Setup

**Comment by daissatou2** [comment]
@mtuchi please review this issue. Two outstanding things before I move it to backlog. 
1. We have control over how we want the file to be named. Please let us know which naming convention would make parsing the date the simplest, if any. For example, should we use bc_actuals_YY_MM_DD.csv, YY_MM_DD_bc_actuals.csv, or something else? I'll update the testing steps after we agree on a file naming convention. 
2. Is the OpenFn Sharepoint site login on LP? I see in this [issue](https://github.com/OpenFn/akf/issues/2#issuecomment-1635954085) it was configured on the platform as `mtuchi-akf` but I can't find it in LP. We want to use the same cred for this issue.

**Comment by daissatou2** [comment]
@mtuchi I've updated the output section with test steps.

**Comment by mtuchi** [comment]
> @mtuchi I've updated the output section with test steps given this naming convention: `bc_actuals_YY_MM_DD.csv`

@daissatou2 i have added the cursor for `getActuals` and improve the job code to use the latest version of msgraph, See PR #5 

Two things you need to know before testing. 
1. I have updated the file naming convention to follow `file_name-YYYY_MM_DD` this makes it easy to separate a file name and it's date. An example of file name `bc_actuals-2023_07_11.csv`
2. To test on platform-app, you need to use the latest version of `msgraph` `v0.3.0`. Use the download icon on to set the version for the msgraph 

Let me know if you need further assistance

**Comment by mtuchi** [comment]
> ~1. I have updated the file naming convention to follow `file_name-YYYY_MM_DD` this makes it easy to separate a file name and it's date. An example of file name `bc_actuals-2023_07_11.csv`~
> 2. To test on platform-app, you need to use the latest version of `msgraph` `v0.3.0`. Use the download icon on to set the version for the msgraph

@daissatou2  i have made some adjustment to support file naming convention `file_name_YY_MM_DD` and `file_name_YYYY_MM_DD`, You can proceed testing now on platform-app with latest version of `msgraph v0.3.0`

**Comment by daissatou2** [comment]
@mtuchi according to the [logs](https://www.openfn.org/projects/akf-bc-aims-integration/runs/064c1433-3b72-7716-b740-a3c63c359617), the job is currently downloading and sending data from 3 files to SF. See the load to SF [log](https://www.openfn.org/projects/akf-bc-aims-integration/runs/064c1433-ada6-7d1e-9d0a-da7f9c381043), where we bulk upsert to SF 3 times. **It should always only download 1 file each run**.  If for some reason more than one file matches your filtering criteria (which shouldn't be the case with the current test data on the site), the job should fail. With the files currently in the bc_actuals_export [folder](https://openfnorg.sharepoint.com/Shared%20Documents/Forms/AllItems.aspx?id=%2FShared%20Documents%2FBC%20Actuals%20Export&viewid=aaf19eb4%2D2159%2D42a1%2D81e9%2Da392b96bc5e4), and the cursor `2023-05-26` your job should return the file named `bc_actuals_2023_06_10.csv`. 

**Please also implement this new request:**
If there are zero files in the folder which match your filtering criteria, the job should throw an error with the following message: "No file found."

**Comment by mtuchi** [comment]
@daissatou2 i have update the job to fetch csv file from https://akdngva.sharepoint.com/sites/AKFDataIntegrations, please add sample test file in that sharepoint and re-run the job to test the cursor

**Comment by daissatou2** [comment]
@mtuchi as discussed these are changes to be made to the cursor logic:

**Manual Cursor**
1. We can safely assume that when a user explicitly clears state and uses the manual cursor, it will be to fetch a specific file. Therefore, when the job runs against the manual cursor, the job should search for a file in the `BC Actuals Exports` folder whose date **equals the manual cursor date**. For example, if the manual cursor is set to `2023-05-26`, and the job is run with state cleared, the job should return the file `bc_actuals_2023_05_26.csv`. 
2. If no such file with the exact date is found, the job should fail with the error message "no file found for manual cursor date 2023-05-26". 
3. If more than one file is found with that date, the job should fail with the error message "duplicate files found for cursor date 2023-05-26."


**Automated cursor**
The job is currently working as expected for the automated cursor except for these edge cases:
1. If the job finds more than one file which has a date that is greater or equal to the cursor, **it should return the file with the latest date.** For example, if the cursor = `2023-08-01` and the `BC Actual Export` folder contains the following files:  `bc_actuals_2023_05_26.csv`, `bc_actuals_2023_08_26.csv`, `bc_actuals_2023_08_30.csv`. The job should only download the `bc_actuals_2023_08_30.csv` file. 
3. Just like with the manual cursor logic, if no file is found, the job should fail with the error message "no file found for cursor date 2023-05-26"
4. Just like with the manual cursor logic, if two files are found for some reason (say, for example, if `bc_actuals_2023_08_30.csv` from above  is a duplicate) the job should fail with the error message "duplicate files found for cursor date 2023-05-26."
